// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-variants/Editorial.tsx": () => import("../components/mockups/hero-variants/Editorial.tsx"),
  "./components/mockups/hero-variants/Precision.tsx": () => import("../components/mockups/hero-variants/Precision.tsx")
};
